//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.06 at 03:15:59 PM CEST 
//


package mpstyle.ws.order;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the order package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: order
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrderReservation }
     * 
     */
    public OrderReservation createOrderReservation() {
        return new OrderReservation();
    }

    /**
     * Create an instance of {@link OrderReservation.OrderItems }
     * 
     */
    public OrderReservation.OrderItems createOrderReservationOrderItems() {
        return new OrderReservation.OrderItems();
    }

    /**
     * Create an instance of {@link OrderReservation.OrderItems.OrderItem }
     * 
     */
    public OrderReservation.OrderItems.OrderItem createOrderReservationOrderItemsOrderItem() {
        return new OrderReservation.OrderItems.OrderItem();
    }

}
