//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.06 at 03:15:59 PM CEST 
//


package mpstyle.ws.order;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="order_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reservation_status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="order_items">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="order_item" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="order_item_seq_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="sku" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="qty" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="reservation_facility" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orderId",
    "reservationStatus",
    "orderItems"
})
@XmlRootElement(name = "order_reservation")
public class OrderReservation {

    @XmlElement(name = "order_id", required = true)
    protected String orderId;
    @XmlElement(name = "reservation_status", required = true)
    protected String reservationStatus;
    @XmlElement(name = "order_items", required = true)
    protected OrderReservation.OrderItems orderItems;

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderId(String value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the reservationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReservationStatus() {
        return reservationStatus;
    }

    /**
     * Sets the value of the reservationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReservationStatus(String value) {
        this.reservationStatus = value;
    }

    /**
     * Gets the value of the orderItems property.
     * 
     * @return
     *     possible object is
     *     {@link OrderItems }
     *     
     */
    public OrderItems getOrderItems() {
        return orderItems;
    }

    /**
     * Sets the value of the orderItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderItems }
     *     
     */
    public void setOrderItems(OrderItems value) {
        this.orderItems = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="order_item" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="order_item_seq_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="sku" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="qty" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="reservation_facility" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "orderItem"
    })
    public static class OrderItems {

        @XmlElement(name = "order_item")
        protected List<OrderItem> orderItem;

        /**
         * Gets the value of the orderItem property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the orderItem property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOrderItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OrderItem }
         * 
         * 
         */
        public List<OrderItem> getOrderItem() {
            if (orderItem == null) {
                orderItem = new ArrayList<OrderItem>();
            }
            return this.orderItem;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="order_item_seq_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="sku" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="qty" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="reservation_facility" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "orderItemSeqId",
            "sku",
            "qty",
            "reservation_facility"
        })
        public static class OrderItem {

            @XmlElement(name = "order_item_seq_id", required = true)
            protected String orderItemSeqId;
            @XmlElement(required = true)
            protected String sku;
            @XmlElement(required = true)
            protected BigDecimal qty;
            @XmlElement(required = true)
            protected String reservation_facility;

            /**
             * Gets the value of the orderItemSeqId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrderItemSeqId() {
                return orderItemSeqId;
            }

            /**
             * Sets the value of the orderItemSeqId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrderItemSeqId(String value) {
                this.orderItemSeqId = value;
            }

            /**
             * Gets the value of the sku property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSku() {
                return sku;
            }

            /**
             * Sets the value of the sku property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSku(String value) {
                this.sku = value;
            }

            /**
             * Gets the value of the qty property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getQty() {
                return qty;
            }

            /**
             * Sets the value of the qty property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setQty(BigDecimal value) {
                this.qty = value;
            }
            
            /**
             * Sets the value of the reservation_facility property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReservationFacility(String value) {
                this.reservation_facility = value;
            }
            
             /**
             * Gets the value of the reservation_facility property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReservationFacility() {
                return this.reservation_facility;
            }

        }

    }

}
